
name: 'snowplow_event_atomisation'
version: '0.0.1'
config-version: 2


profile: 'default-bigquery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  snowplow_event_atomisation:
    snowplow__incremental_materialization: "snowplow_incremental"
